module.exports = {
  Accessibility: require('./Accessibility').Accessibility,
  Browser: require('./Browser').Browser,
  BrowserContext: require('./Browser').BrowserContext,
  BrowserFetcher: require('./BrowserFetcher').BrowserFetcher,
  ConsoleMessage: require('./Page').ConsoleMessage,
  Dialog: require('./Dialog').Dialog,
  ElementHandle: require('./JSHandle').ElementHandle,
  ExecutionContext: require('./ExecutionContext').ExecutionContext,
  Frame: require('./FrameManager').Frame,
  JSHandle: require('./JSHandle').JSHandle,
  Keyboard: require('./Input').Keyboard,
  Mouse: require('./Input').Mouse,
  Page: require('./Page').Page,
  Puppeteer: require('./Puppeteer').Puppeteer,
  Request: require('./NetworkManager').Request,
  Response: require('./NetworkManager').Response,
  SecurityDetails: require('./NetworkManager').SecurityDetails,
  Target: require('./Browser').Target,
  Touchscreen: require('./Input').Touchscreen,
  TimeoutError: require('./Errors').TimeoutError,
};
