name: Bug report
description: File a bug report
title: '[Bug]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out this bug report!
        **Before filling out this report**, please check our [Troubleshooting](https://pptr.dev/troubleshooting) guide for solutions to common issues.
        Also, verify the problem is *related to packages maintained by Puppeteer* (this does not include `puppeteer-extra`, `expect-puppeteer`, etc.).
  - type: textarea
    id: summary
    attributes:
      label: Bug description
      description: What did you do? What did you expect to happen? What actually happened instead?
      value: |
        Steps to reproduce the problem:

        1. …
    validations:
      required: true
  - type: input
    id: puppeteer-version
    attributes:
      label: Puppeteer version
      description: What version of Puppeteer are you running?
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: What version of Node.js are you running?
    validations:
      required: true
  - type: input
    id: npm-version
    attributes:
      label: npm version
      description: What version of npm are you running?
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration file
      description: |
        Please copy and paste your configuration file [[Docs](https://pptr.dev/guides/configuration/)]. 
        *No need for backticks — this automatically gets formatted into code.*
      render: JavaScript
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. 
        *No need for backticks — this automatically gets formatted into code.*
      render: Shell
