name: Bug report
description: File a bug report
title: '[Bug]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        ### Thanks for taking the time to fill out this bug report!

        **Before filling out this report**, please check our
        [Troubleshooting](https://pptr.dev/troubleshooting) guide for solutions
        to common issues.
  - id: summary
    type: textarea
    attributes:
      label: Bug expectation
      description: What do you expect to happen? What actually happened instead?
      placeholder: |
        I expected ...

        What happened instead was ...
    validations:
      required: true
  - id: behavior
    type: checkboxes
    attributes:
      label: Bug behavior
      description: >
        How does the bug behave? Does it happen very rarely (flaky)? If there is
        a PDF problem, make sure the script writes the PDF somewhere in the
        current working directory. *Note: PDF implies no error.*
      options:
        - label: Flaky
        - label: PDF
  - id: mvce
    type: textarea
    attributes:
      label: Minimal, reproducible example
      description: >
        Provide a [minimal, reproducible
        example](https://stackoverflow.com/help/minimal-reproducible-example).
        *No need for backticks — this automatically gets formatted into code.*
      render: TypeScript
      placeholder: |
        import puppeteer from 'puppeteer'; // TS/ESM are all supported.

        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('https://news.google.com/news/');
          await page.screenshot({path: 'news.png', fullPage: true});
          await browser.close();
        })();
    validations:
      required: true
  - id: error
    type: input
    attributes:
      label: Error string
      description: >
        Provide the bug's error. For example, `throw new Error('Something went
        wrong')` would have the error `Something went wrong`. **If the script
        does not throw**, write `no error` (case insensitive).
      placeholder: Something went wrong
    validations:
      required: true
  - id: puppeteer-configuration
    type: textarea
    attributes:
      label: Puppeteer configuration
      description: >
        Copy and paste your [configuration
        file](https://pptr.dev/guides/configuration/) (if applicable). *No need
        for backticks — this automatically gets formatted into code.*
      render: TypeScript
  - id: puppeteer-version
    type: input
    attributes:
      label: Puppeteer version
      description: |
        What version of Puppeteer are you running? *This must be a valid semver
        tag.*
    validations:
      required: true
  - id: node-version
    type: input
    attributes:
      label: Node version
      description: |
        What supported version of Node.js are you running? *This must be a valid
        semver tag.*
    validations:
      required: true
  - id: pkg-mgr
    type: dropdown
    attributes:
      label: Package manager
      description: What package manager are you running?
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - id: pkg-mgr-version
    type: input
    attributes:
      label: Package manager version
      description: |
        What version of the package manager are you running? *This must be a
        valid semver tag.*
    validations:
      required: true
  - id: operating-system
    type: dropdown
    attributes:
      label: Operating system
      description: What supported operating system are you running?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
