blank_issues_enabled: true
contact_links:
  - name: General Puppeteer questions
    url: https://stackoverflow.com/questions/tagged/puppeteer
    about: For general technical questions or “how to” guidance, please search StackOverflow for questions tagged “puppeteer” or create a new post.
