name: Feature
description: File a feature request
title: '[Feature]: '
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out a feature request!
        **Before filling out this report**, please check [existing feature requests](https://github.com/puppeteer/puppeteer/issues?q=is%3Aissue++label%3Afeature+) and see if your feature has already been proposed.
  - type: textarea
    id: summary
    attributes:
      label: Feature description
      description: Please describe your feature request with as many details as possible.
    validations:
      required: true
