name: Bug for @puppeteer/browsers
description: File a bug report specifically about the `@puppeteer/browsers` package.
title: '[Bug]: '
labels: [bug, '@puppeteer/browsers']
body:
  - type: textarea
    id: summary
    attributes:
      label: Steps to reproduce
      description: Please describe steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
      description: What is the behaviour you expect.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual results
      description: What is the observed behaviour.
    validations:
      required: true
