/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Puppeteer Guides',
        keywords: ['guides'],
      },
      collapsed: false,
      items: [
        'guides/chrome-extensions',
        'guides/configuration',
        'guides/debugging',
        'guides/docker',
        'guides/request-interception',
      ],
    },
    'chromium-support',
    'troubleshooting',
    'contributing',
    'faq',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};
