/**
 * @license
 * Copyright 2024 Google Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Puppeteer Guides',
        keywords: ['guides'],
      },
      collapsed: false,
      items: [
        'guides/configuration',
        'guides/query-selectors',
        'guides/locators',
        'guides/evaluate-javascript',
        'guides/docker',
        'guides/request-interception',
        'guides/chrome-extensions',
        'guides/debugging',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index',
        title: 'Puppeteer Integrations',
        keywords: ['integrations'],
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: 'Angular Schematics',
          id: 'integrations/ng-schematics',
        },
      ],
    },
    'webdriver-bidi',
    'chromium-support',
    'troubleshooting',
    'contributing',
    'faq',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  browsersApi: [
    {
      type: 'autogenerated',
      dirName: 'browsers-api',
    },
  ],
};
