name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Querying")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              # Dry run
              # github.rest.actions.deleteActionsCacheById({
              #   owner: context.repo.owner,
              #   repo: context.repo.repo,
              #   cache_id: cache.id,
              # })
            }
            console.log("Clear completed")
