name: Full CI

# Declare default permissions as read only.
permissions:
  contents: read

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: full-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ github.event.label.name == 'full-ci' }}
    uses: ./.github/workflows/ci.yml
