name: publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish puppeteer
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish
      - name: Publish puppeteer-core
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER_CORE}}
        run: |
          utils/prepare_puppeteer_core.js
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish
