name: publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish puppeteer
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          echo "Publishing puppeteer"
          npm publish
          # DEPRECATED_RANGE=$(node utils/get_deprecated_version_range.js)
          # echo "Deprecating old puppeteer versions: $DEPRECATED_RANGE"
          # npm deprecate puppeteer@$DEPRECATED_RANGE "Version no longer supported. Upgrade to @latest"
      - name: Publish puppeteer-core
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER_CORE}}
        run: |
          utils/prepare_puppeteer_core.js
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish

  post-publish:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      actions: read|write
      contents: read|write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Append `-post` to version
        id: post-version
        run: |
          npm version --no-git-tag-version --no-commit-hooks "$(jq -r .version ./package.json)-post"
          echo ::set-output name=VERSION::$(jq -r .version ./package.json)
      - name: Build
        run: |
          npm install
          npm run build
          npm run doc
      - name: Commit and push
        run: |
          git config user.name 'Github'
          git config user.email '<noreply@github.com>'
          git add -A
          git commit -m "chore: bump version to ${{ steps.post-version.outputs.VERSION }}"
          git push
