name: release-please

# Declare default permissions as read only.
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  docs:
    name: Docs
    needs: release-please
    permissions:
      contents: write
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    secrets:
      ALGOLIA_CRAWLER_API_KEY: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
      ALGOLIA_CRAWLER_ID: ${{ secrets.ALGOLIA_CRAWLER_ID }}
      ALGOLIA_CRAWLER_USER_ID: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
